### ISSUE TITLE
Como bajarse los cambios que hay en GitHub

### ISSUE THREAD

**Issue by felipe-barreto** [adrianocanavero/trabajo-final-python#1]
Lo que hice es bajarme todos los archivos que están en GitHub (usando git clone, esto me crea una carpeta donde van todos los archivos) modificar algo y subir los cambios, mi pregunta es ¿tengo que hacer esto cada vez que quiero modificar algo? Porque de esta forma me crea una carpeta nueva cada vez que lo hago entonces voy acumulando una carpeta nueva para cada modificación o sino podría usar git clone modificar algo, subirlo, borrar la carpeta, y la próxima vez que quiera modificar algo uso git clone otra vez y de esta forma no se me crean muchas carpetas.
Esta consulta de paso sirve como prueba de las issues.

@tomibarbieri

**Comment by tomibarbieri** [comment]
Felipe, buenisimo, me llego la issue, asi que la prueba funcionó.
Es importante que prueben algunos tutoriales que les comparti la otra clase, ahora les mando de nuevo -> https://catedras.linti.unlp.edu.ar/mod/wiki/view.php?pageid=615 (ahi hay varios links para chusmear)

Clonar un proyecto con `git clone url-repositorio` como decis bien te genera la instancia del repositorio en tu maquina.

Luego para actualizar tu repo a lo ultimo se hace con `git pull` y para subir cambios `git push`. Antes de subir cambios hay que hacer ademas los commits con `git commit -m 'mensaje del commit'.` y antes de eso incluso agregar los archivos nuevos o las modificaciones con `git add nombre-archivo` para un archivo en particular. Para agregar todo `git add -A` o `git add *` (ojo con esto que uno puede agregar cosas que no quiera).

Siempre es importante dar un seguimiento con `git status` para ver el estado del proyecto.

Un abrazo
Si no se entiene o no pueden, avisame y lo vemos con una prueba.

**Comment by felipe-barreto** [comment]
Genial, después lo pruebo. Gracias por responder.
Saludos!
