### ISSUE TITLE
Aveces aparece un error

### ISSUE THREAD

**Issue by felipe-barreto** [adrianocanavero/trabajo-final-python#2]
En el módulo m_tablero, en la función calcular_puntos cada tanto da error valores_letras[letra]. Originalmente el error lo daba la que actualmente es la línea 55, pero puse un print en la línea 40 que usa valores_letras[letra] y ahora el error lo da ahí. 
En la terminal aparece KeyError: 'o', y no encontré qué puede ser.
El error es poco frecuente, por decir un aproximado cada 40 palabras que se ingresan en una da este error, y no encontré qué tienen en común las palabras con las que da error. 
Saludos.

@tomibarbieri

**Comment by tomibarbieri** [comment]
Hola chicos!
Hoy a la tarde lo pruebo en la maquina virtual bajando las ultimas actualizaciones a ver que esta pasando ahi.
Tienen para adjuntarme una captura de pantalla del error? O copiarme el codigo exacto del error?
Gracias!

**Comment by felipe-barreto** [comment]
![Foto](https://user-images.githubusercontent.com/63361957/84062235-66509600-a995-11ea-8fa2-ba7747e424d4.png)

 @tomibarbieri

**Comment by felipe-barreto** [comment]
Al final el problema era que no teníamos en cuenta qué pasaba cuando la máquina no encuentra una palabra, entonces intentaba calcular los puntos para una palabra que no había encontrado y daba error. Así que este problema ya está solucionado.

@tomibarbieri

**Comment by tomibarbieri** [comment]
Bien buenisimo!
