### ISSUE TITLE
Error al empezar una nueva partida

### ISSUE THREAD

**Issue by felipe-barreto** [adrianocanavero/trabajo-final-python#4]
Aveces (pasa bastante seguido) al empezar una nueva partida (hasta ahora nunca dio el error al cargar una partida) se pone a buscar palabras random de cualquier cantidad de letras (aveces son más o menos 7 y aveces más de 20). Pareciera que si estás jugando una partida, la posponés y después intentás empezar una nueva (sin haber cerrado el juego) es un poco más probable que pase, pero puede que haya sido casualidad. 
Saludos.

@tomibarbieri 

![Error](https://user-images.githubusercontent.com/63361957/85505044-c6fde680-b5c3-11ea-8313-e00f42696421.png)

**Comment by tomibarbieri** [comment]
Hola chicxs, como estan?
En que parte estan haciendo esa impresion para ver donde se esta llamando o hacer un seguimiento de porque comienza a buscar.
Saludos!

**Comment by felipe-barreto** [comment]
Ya está solucionado, al empezar una nueva partida no se reseteaban las letras de la máquina y buscaba palabras con muchas letras.
Saludos.
@tomibarbieri
