### ISSUE TITLE
Consultas sobre la primer entrega del trabajo

### ISSUE THREAD

**Issue by felipe-barreto** [adrianocanavero/trabajo-final-python#5]
Hola, unas consultas:

+ La división en directorios que se pide, ¿es la división en módulos que hicimos o tenemos que hacer otra cosa?

+ En las pautas se pide que haya un botón iniciar, ¿es obligatorio que lo hagamos? O sea, ¿nos bajan nota si no lo hacemos? Porque tenemos un menú con partida nueva y cargar partida (además de otras cosas) y no creo que tenga mucho sentido que después de elegir una partida haya que apretar un botón iniciar. Igual es muy fácil hacerlo, así que no habría problema.

+ Si no cumplimos con todos los items que se piden, ¿está desaprobado el trabajo o solamente es menos nota? Porque el único item con el que probablemente no cumplamos es tener los tres tableros. Si es obligatorio para aprobar lo vamos a hacer pero sino por ahí no porque lleva más tiempo hacerlo que las otras cosas que nos faltan y tenemos varios exámenes.

Saludos.

@tomibarbieri

**Comment by tomibarbieri** [comment]
Hola Felipe, ¿cómo están?

La planilla es orientadora, no es que tiene que estar todo TAL CUAL esta ahi, y claramente hay cosas que son mas importantes que otras. Por ejemplo si documentan con docstrings van a sumar unos puntitos pero si no lo hacen no los voy a desaprobar.

En cuanto a la division en carpetas yo tomo como referencia la modularización también por lo que pueden ser archivos también (como tienen ustedes).

En cuanto al botón iniciar no es necesario que lo hagan, ya con el menú inicial me parece suficiente.

Si cumplen con absolutamente todos los puntos tendrían la mayor nota, pero si les faltan algunos no es que van a desaprobar, muchos de los puntos son mas de nota conceptual. En cuanto a los tableros , vayan pensando de que forma lo pueden implementar pero no los voy a desaprobar por ese tema, quedense tranqui.

Saludos!

**Comment by felipe-barreto** [comment]
Genial, gracias por responder!

@tomibarbieri
