### ISSUE TITLE
Problema con linux

### ISSUE THREAD

**Issue by adrianocanavero** [adrianocanavero/trabajo-final-python#6]
Ejecute el juego en la maquina virtual modificando algunas partes del codigo (por ejemplo, el import de winsound), pero tirar error al querer hacer un read de Window con pysimplegui. Probe ejecutar un ejemplo de una ventana simple con un texto y tambien tira error.

![error linux](https://user-images.githubusercontent.com/62101495/85954986-eb561c00-b951-11ea-9b58-4f7dbfc7902c.jpg)

**Comment by adrianocanavero** [comment]
@tomibarbieri

**Comment by felipe-barreto** [comment]
O sea el problema es que no funciona en Linux.
@tomibarbieri

**Comment by tomibarbieri** [comment]
Donde lo probaron en linux? en la maquina virtual? Puede ser un error de la version tambien. En la maquina virtual esta la version 3 y pico cuando la version final es 4.20
Ahora pruebo en mi maquina virtual q esta actualizada a ver si tiene el mismo problema. 
Ya que en las versiones mas nuevas no anta el .Read con mayuscula

**Comment by tomibarbieri** [comment]
Cuando hablo de version me refiero a la version de PySimpleGUI

**Comment by tomibarbieri** [comment]
Ahi recien vi que lo ejecutaron desde la maquina virtual, es probable que sea ese problema. Y consulta la libreria esa de sonido que version instalaron, con pip , no me deja (asi lo puedo probar). Un abrazo

**Comment by tomibarbieri** [comment]
AH por lo que veo es solo de windows. Lo que podemos hacer para esa libreria es condicionarla a si estas ejecutando desde windows o linux e importarla solo si se puede.

**Comment by adrianocanavero** [comment]
la libreria esa de sonido es exclusiva de windows me parece. Por eso la ejecute con un try. Despues voy a buscar una libreria que sea multiplataforma. ¿Podrias probar haciendole un try except al import de esa libreria?  (como en la foto que pase en esta issue).

Quise actualizar el pysimplegui de la maquina virtual y no pude, tampoco me dejaba desinstalar el que estaba instalado.
Gracias por la respuesta!

**Comment by tomibarbieri** [comment]
Para actualizar en la maquina tenes que hacer `pip install pysimplegui=4.20.0` (no recuerdo si iba con comillas el numero o no). Adjunto imagen de como se ejecuta sacando la libreria solo de windows.

<img width="1098" alt="Captura de Pantalla 2020-06-28 a la(s) 21 52 49" src="https://user-images.githubusercontent.com/3981019/85962988-f75dd000-b989-11ea-8e4b-6d32b4633eb4.png">

**Comment by adrianocanavero** [comment]
buenisimo, gracias!
