### ISSUE TITLE
Consulta sobre "Terminar" y licencias

### ISSUE THREAD

**Issue by felipe-barreto** [adrianocanavero/trabajo-final-python#7]
Hola, dos consultas, ¿al presionar el botón terminar hay que hacer lo mismo que si se acaba el tiempo o las fichas (o sea restar el puntaje de las letras del atril, ver quién ganó, etc.)? ¿O se cierra el juego y ya está?

La otra consulta es ¿qué sería incluir una licencia de código?

Saludos.

@tomibarbieri

**Comment by tomibarbieri** [comment]
Hola Felipe, como estas? En cuanto a la primer pregunta. Si ustedes tienen alguna opcion que sea guardar partida, en ese caso la funcion terminar hace lo que vos decis, calcular el puntaje final, mostrarlo y finalizar.

En cuanto a licencia del código, la idea es que puedan investigar un poco y elegir alguna de las licencias para aplicarla a su codigo. Si bien es algo mas simbólico, esta bueno que lo sepan y comprendan para cuando les toque aplicarlo o verlo en sistemas reales de codigo abierto.

Les dejo un articulo para que vayan leyendo: https://www.maestrodelacomputacion.net/que-son-las-licencias-de-codigo-abierto/

Un abrazo

**Comment by felipe-barreto** [comment]
Oka, gracias!
