### ISSUE TITLE
Sonidos

### ISSUE THREAD

**Issue by adrianocanavero** [adrianocanavero/trabajo-final-python#8]
@tomibarbieri 

Hola Tom! Queria preguntarte si podias probar si en tu pc con linux funciona el juego con los sonidos, o si funciona y no se escuchan, o si directamente no funciona. Probe con la maquina virtual pero tiene problema de import con unos modulos y no se si sera por la version de python que tiene o otra cosa. Saludos!

**Comment by adrianocanavero** [comment]
@tomibarbieri me olvide de decir que la parte de sonidos esta implementada con un modulo de pygame, asi que hay que instalar eso

**Comment by tomibarbieri** [comment]
Bien, chicos, el miercoles lo voy a probar, mandenme bien las librerias que estan usando, ejecutando en su maquina pip freeze (esto dice la version exacta de las librerias de python, y clasifiquen las que importan ustedes)
Abrazo

**Comment by adrianocanavero** [comment]
Las librerias que usamos son PySimpleGui 4.18.2, Pattern 3.6 y pygame 1.9.6. La que esta en cuestion por su funcionamiento en linux seria pygame, aunque tengo entendido que no debería haber problema.
Gracias!

**Comment by tomibarbieri** [comment]
Bien, ahi estuve probando, y no se escuchan los sonidos, pero si se ejecuta el juego. Voy a seguir viendo a ver que onda pero no hay problema si no funciona el sonido ya que es un requerimiento adicional.
Un Abrazo

**Comment by adrianocanavero** [comment]
buenisimo, gracias por fijarte tom!
